server:
  port: 8080
#  address: 127.0.0.1  # Ngnix ip

spring:
  application:
    name: yookassa

yookassa:
  base-url: https://api.yookassa.ru
  shop-id: ${SHOP_ID}
  secret-key: ${SECRET_KEY}
  type: redirect
  return-url: https://yandex.ru/internet/
  allowed-ips:
    185.71.76.0/27, 
    185.71.77.0/27, 
    77.75.153.0/25, 
    77.75.156.11, 
    77.75.156.35, 
    77.75.154.128/25, 
    2a02:5180::/32